<?
// ############################################################
// # StatIt                                                   #
// ############################################################
// # by Helge Orthmann                                        #
// # Contact: otter@otterware.de                              #
// # Homepage: http://www.otterware.de                        #
// # Translated by: David Asin Sanchez     to: Spanish        #
// ############################################################
// # Leave this header in this file !                         #
// ############################################################
// fondos de tabla
$st_tabla1 = "#408488";
$st_tabla2 = "#58AC97";
$st_tabla3 = "#58ACB0";
// archivo de fondo de web (si no se pone se utilizará el bgcolor - color de fondo -)
$st_backg = "grund.gif";
// estilo del cuerpo de la web
$st_text = "#000000"; 
$st_link = "#FF0000";
$st_alink = "#FF0000";
$st_vlink = "#FF0000";
$st_bgcolor = "#FFFFFF";
// text style
$st_textsize1 = "4"; // greater text (1-7)
$st_textsize2 = "1"; // smaller text (1-7)
$st_textfont = "Verdana";
// max height and width of the bars
$st_dwidth = "100";
$st_dheight = "100";
// want to show IP address in statistic ("on" or "off")?
$st_showip = "on";
// want to show log files in statistic ("on" or "off")?
$st_showlog = "on";
// lenguaje
$st_l1 = "estadística";
$st_l2 = "últimos visitantes";
$st_l3 = "hora de la última visita";
$st_l4 = "IP";
$st_l5 = "nombre del host";
$st_l6 = "lenguaje";
$st_l7 = "navegador";
$st_l8 = "sistema operativo";
$st_l9 = "navegante";
$st_l10 = "visitantes en el último mes";
$st_l11 = "estadísticas del día";
$st_l12 = "semana-días";
$st_l13 = "estadística anual";
$st_l14 = "otros";
$st_l15 = "dominios más comunes del navegante";
$st_l16 = "dominio";
$st_l17 = "impactos";
$st_l18 = "por";
$st_l19 = "su";
$st_l20 = "mo";
$st_l21 = "tu";
$st_l22 = "we"; 
$st_l23 = "th";
$st_l24 = "fr";
$st_l25 = "sa";
$st_l26 = "tamaño de pantalla";
$st_l27 = "colores";
$st_l28 = "hoy";
$st_l29 = "ayer";
$st_l30 = "mes actual";
$st_l31 = "mes más activo";
$st_l32 = "día más activo";
$st_l33 = "hora más activa";
$st_l34 = "navegador más usado";
$st_l35 = "sistema más usado";
$st_l36 = "tamaño de pantalla más usado";
$st_l37 = "colores más usados";
$st_l38 = "informacion breve del visitante";
$st_l39 = "en punto";
$st_l40 = "Enero";
$st_l41 = "Febrero";
$st_l42 = "Marzo";
$st_l43 = "Abril";
$st_l44 = "Mayo";
$st_l45 = "Junio";
$st_l46 = "Julio";
$st_l47 = "Agosto";
$st_l48 = "Septiembre";
$st_l49 = "Octubre";
$st_l50 = "Noviembre";
$st_l51 = "Diciembre";
$st_l52 = "media";
$st_l53 = "solicitudes de websites";
$st_l54 = "site";
$st_l55 = "visitantes totales";
$st_l56 = "tamaño de los ficheros log";
$st_l57 = "origen de los visitantes";
$st_l58 = "nivel de dominio superior";
$st_l59 = "territorios";
$st_l60 = "Europa";
$st_l61 = "América";
$st_l62 = "África";
$st_l63 = "Asia";
$st_l64 = "Oceanía";
$st_l65 = "Federación rusa";
$st_l66 = "Antártida";
$st_l67 = "Desconocido";
$st_l68 = "origen más frecuente";
$st_l69 = "nivel de dominio superior más frecuente";
$st_l70 = "territorio más frecuente";
$st_l71 = "sitio más frecuente";
$st_l72 = "Día más frecuente";
$st_l73 = "total";
$st_l74 = "searchengine";
$st_l75 = "queries";
$st_l76 = "top query";
$st_l77 = "file";
$st_l78 = "size (bytes)";
$st_l79 = "backups";
$st_l80 = "file month.year";
// admin.php3
$st_la1 = "estadísticas de área de administración";
$st_la2 = "borrar ficheros log";
$st_la3 = "borrar valores";
$st_la4 = "login";
$st_la5 = "password";
$st_la6 = "repetición";
$st_la7 = "borrar";
$st_la8 = "cambiado";
$st_la9 = "editar _config.inc";
$st_la10 = "autentificación";
$st_la11 = "on";
$st_la12 = "off";
$st_la13 = "altura de las barras";
$st_la14 = "anchura de las barras";
$st_la15 = "estadísticas de dirección IP";
$st_la16 = "las contraseñas no coinciden";
$st_la17 = "error";
$st_la18 = "mensaje(s)";
$st_la19 = "backup";  //the backup
$st_la20 = "backup";
$st_la21 = "restaurar";
$st_la22 = "La copia no tuvo éxito";
$st_la23 = "tiene backup";
$st_la24 = "restaurado";
$st_la25 = "no hay backup disponible";
$st_la26 = "ficheros log";
$st_la27 = "Última fecha de backup";
$st_la28 = "password -> mínimo 4 caracteres";
$st_la29 = "edit _short.inc";
$st_la30 = "visible counter";
$st_la31 = "text";
$st_la32 = "graphical";
$st_la33 = "number of digits counter";
$st_la34 = "show unique visitors";
$st_la35 = "max 8 digists for counter";
$st_la36 = "include path/statit.php3 must set \nto first line in calling page";
$st_la37 = "text size counter";
$st_la38 = "text color counter";
$st_la39 = "background color counter";
$st_la40 = "font counter";
$st_la41 = "color table";
$st_la42 = "color";
$st_la43 = "max text counter size 6";
$st_la44 = "color format #123456";
$st_la45 = "reload blocker";
$st_la46 = "timezone server";
$st_la47 = "format +(-)time";
$st_la48 = "background file";
$st_la49 = "doesn't exist";
$st_la50 = "part";
$st_la51 = "big";
$st_la52 = "small";
$st_la53 = "font";
$st_la54 = "background color";
$st_la55 = "include path/statit.php3 must set in every\nsite which will be count!";
$st_la57 = "server block (s1,s2)";
$st_la58 = "fontsize from 1-7";
$st_la59 = "server blocked";
$st_la60 = "no server will be blocked";
$st_la61 = "show log files";
?>